### ISSUE TITLE
Sunrise and Sunset are not accurate

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#1]
The data provided by Met.No no longer comes with Sunrise and Sunset data, so I have had to find a different source.
The best suitable provider I could find was at https://api.sunrise-sunset.org but it does not seem to match the times provided by my weather apps...

**Comment by fkru** [comment]
> The data provided by Met.No no longer comes with Sunrise and Sunset data, so I have had to find a different source. The best suitable provider I could find was at https://api.sunrise-sunset.org but it does not seem to match the times provided by my weather apps...

I can confirm this, I see differences up to 30 minutes. Maybe this is worth a try: https://www.timeanddate.com/company/

**Comment by fkru** [comment]
Unfortunately, their API's are not for free after three months.

**Comment by solbu** [comment]
Met.no has an API that can be used.
https://api.met.no/weatherapi/sunrise/2.0/documentation

**Comment by blackadderkate** [comment]
> Met.no has an API that can be used. https://api.met.no/weatherapi/sunrise/2.0/documentation

I looked at this API when I was first preparing to release the widget, but it requires mandatory Timezone information (the offset parameter) - which is impossible to calculate from just a latitude and longtitude.
So to prevent the release of the widget being delayed I decided to use the sunrise-sunset API instead, even though I knew it didn't seem to be entirely accurate.

The situation has changed now that I have implemented the Location Search feature, and it would be relatively easy to add Timezone data to the relevant databases.
But there is still an issue with Daylight Savings - in order to correctly calculate the offset for a location, I need to know the DST start/end dates for that Timezone otherwise the times could be out by ± 1 hour!

That information looks as though it _might_ be available in the QML Core locale API - but I need to experiment to know for sure.

**Comment by fkru** [comment]
Let me come back to https://sunrise-sunset.org/. I am puzzled by the fact that their data provided on their website are different from the ones shown in the widget. For example, https://sunrise-sunset.org/search?location=berlin has 7:49 AM and 4:50 PM, while the widget shows  7:24 and 5:01. What do I miss?

**Comment by blackadderkate** [comment]
My widget shows something different for sunrise and sunset (07:42 and 16:43) - much closer to your values, which could be explained by picking different parts of Berlin (and thus latitude and longtitude co-ordinates)...

To be honest, I'm considering removing the sunrise/sunset data from the widget altogether, until I can figure out how to do it properly...

**Comment by blackadderkate** [comment]
FYI - I've been working on this for a couple of days, and I've finally got a working "Prototype" that now downloads sunrise and sunset data from Met.No.

I've [added it as an Alpha release - v2.1.7a](https://github.com/blackadderkate/weather-widget-2/releases) if you want to give it a try - but please Bear in mind that this is a "bleeding edge" release.
The changes to the internal Database structure and the supporting coding is done - but it still needs some GUI modifications, and lots and lots of testing using lots and lots of different locations before it will be ready to release properly...

Note: It is not compatible with your existing configuration, and will ONLY use the Met.No website with "new" met.no locations you add using the Search Button - and it probably contains a million bugs. So use at your own risk...

**Comment by fkru** [comment]
JFYI: Update to version 2.2.2 via KDE store has gone smoothly. The sunrise/sunset issue still exists for metno (OWS works fine).

**Comment by fkru** [comment]
> JFYI: Update to version 2.2.2 via KDE store has gone smoothly. The sunrise/sunset issue still exists for metno (OWS works fine).

Sorry, after a few reloads (after update to 2.2.2) sunset/sunrise data are correct.

**Comment by blackadderkate** [comment]
Great news - I can finally close this issue!
